Agrega estructura base para distill
Psy-Coding/intersemestral_rstats_2022 pull request #1
Opened 2021-12-07 03:31 UTC by nekrum

Estructura para distill y ejemplo de uso:
- Requiere el paquete distill
- Use el paquete renv para que sea mas fácil replicar el repositorio

En teoría debería ser mas sencillo echar a andar en local el sitio

2021-12-07 23:44 UTC, emmaboes requested changes
Hay algunos errores de dedo

2021-12-07 23:44 UTC, emmaboes commented on _site.yml
> +  Facultad de Psycología
Error de dedo: Ps**i**cología

2021-12-07 23:44 UTC, emmaboes commented on docs/search.json
> +      "description": "Estructura de datos orientada a objetoso tabulación de datos\n",
Error de dedo: objetos **insertar espacio** o tabulación

2021-12-07 23:44 UTC, emmaboes commented on docs/search.json
> +          "name": "Ana Gonzales",
El apellido debería ser Gonzalez

2021-12-07 23:44 UTC, emmaboes commented on docs/search.json
> +      "description": "Bienvenido al curso Intersemestra de Rstat 2022\n",
Falta letra: Intersemestra**l**

2021-12-07 23:44 UTC, emmaboes commented on estructura_de_datos.Rmd
> +  Estructura de datos orientada a objetoso tabulación de datos
Error de dedo: objetos **insertar espacio** o tabulación

2021-12-07 23:44 UTC, emmaboes commented on index.Rmd
> +  Bienvenido al curso Intersemestra de Rstat 2022
Falta letra: Intersemestra**l**

2021-12-09 00:30 UTC, nekrum commented on _site.yml
> +  Facultad de Psycología
Hecho

2021-12-09 00:32 UTC, nekrum commented on docs/search.json
> +      "description": "Estructura de datos orientada a objetoso tabulación de datos\n",
Se arreglan con las modificaciones en el archivo estructura_de_datos.Rmd

2021-12-09 00:32 UTC, nekrum commented on docs/search.json
> +          "name": "Ana Gonzales",
Se arreglan con las modificaciones en el archivo estructura_de_datos.Rmd

2021-12-09 00:33 UTC, nekrum commented on docs/search.json
> +      "description": "Bienvenido al curso Intersemestra de Rstat 2022\n",
Se arreglan con las modificaciones en el archivo index.Rmd

2021-12-09 00:33 UTC, nekrum commented on estructura_de_datos.Rmd
> +  Estructura de datos orientada a objetoso tabulación de datos
Hecho  :+1:

2021-12-09 00:33 UTC, nekrum commented on index.Rmd
> +  Bienvenido al curso Intersemestra de Rstat 2022
Hecho :+1:

2021-12-09 00:38 UTC, nekrum commented
Listos los cambios @emmaboes gracias :smile:

2021-12-09 03:19 UTC, emmaboes approved these changes

2021-12-09 18:53 UTC, merged